# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/karla/Diplomski/code/FM_scheduling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/karla/Diplomski/code/FM_scheduling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karla/Diplomski/code/FM_scheduling/CMakeFiles /home/karla/Diplomski/code/FM_scheduling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karla/Diplomski/code/FM_scheduling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FM_scheduling

# Build rule for target.
FM_scheduling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FM_scheduling
.PHONY : FM_scheduling

# fast build rule for target.
FM_scheduling/fast:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/build
.PHONY : FM_scheduling/fast

#=============================================================================
# Target rules for targets named periodic_simulator

# Build rule for target.
periodic_simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 periodic_simulator
.PHONY : periodic_simulator

# fast build rule for target.
periodic_simulator/fast:
	$(MAKE) -f periodic_tasks_simulator/CMakeFiles/periodic_simulator.dir/build.make periodic_tasks_simulator/CMakeFiles/periodic_simulator.dir/build
.PHONY : periodic_simulator/fast

#=============================================================================
# Target rules for targets named periodic_test

# Build rule for target.
periodic_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 periodic_test
.PHONY : periodic_test

# fast build rule for target.
periodic_test/fast:
	$(MAKE) -f periodic_tasks_simulator/CMakeFiles/periodic_test.dir/build.make periodic_tasks_simulator/CMakeFiles/periodic_test.dir/build
.PHONY : periodic_test/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/main.cpp.s
.PHONY : main.cpp.s

src/BWP.o: src/BWP.cpp.o

.PHONY : src/BWP.o

# target to build an object file
src/BWP.cpp.o:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/BWP.cpp.o
.PHONY : src/BWP.cpp.o

src/BWP.i: src/BWP.cpp.i

.PHONY : src/BWP.i

# target to preprocess a source file
src/BWP.cpp.i:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/BWP.cpp.i
.PHONY : src/BWP.cpp.i

src/BWP.s: src/BWP.cpp.s

.PHONY : src/BWP.s

# target to generate assembly for a file
src/BWP.cpp.s:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/BWP.cpp.s
.PHONY : src/BWP.cpp.s

src/EDL.o: src/EDL.cpp.o

.PHONY : src/EDL.o

# target to build an object file
src/EDL.cpp.o:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/EDL.cpp.o
.PHONY : src/EDL.cpp.o

src/EDL.i: src/EDL.cpp.i

.PHONY : src/EDL.i

# target to preprocess a source file
src/EDL.cpp.i:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/EDL.cpp.i
.PHONY : src/EDL.cpp.i

src/EDL.s: src/EDL.cpp.s

.PHONY : src/EDL.s

# target to generate assembly for a file
src/EDL.cpp.s:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/EDL.cpp.s
.PHONY : src/EDL.cpp.s

src/RLP.o: src/RLP.cpp.o

.PHONY : src/RLP.o

# target to build an object file
src/RLP.cpp.o:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/RLP.cpp.o
.PHONY : src/RLP.cpp.o

src/RLP.i: src/RLP.cpp.i

.PHONY : src/RLP.i

# target to preprocess a source file
src/RLP.cpp.i:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/RLP.cpp.i
.PHONY : src/RLP.cpp.i

src/RLP.s: src/RLP.cpp.s

.PHONY : src/RLP.s

# target to generate assembly for a file
src/RLP.cpp.s:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/RLP.cpp.s
.PHONY : src/RLP.cpp.s

src/RTO.o: src/RTO.cpp.o

.PHONY : src/RTO.o

# target to build an object file
src/RTO.cpp.o:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/RTO.cpp.o
.PHONY : src/RTO.cpp.o

src/RTO.i: src/RTO.cpp.i

.PHONY : src/RTO.i

# target to preprocess a source file
src/RTO.cpp.i:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/RTO.cpp.i
.PHONY : src/RTO.cpp.i

src/RTO.s: src/RTO.cpp.s

.PHONY : src/RTO.s

# target to generate assembly for a file
src/RTO.cpp.s:
	$(MAKE) -f CMakeFiles/FM_scheduling.dir/build.make CMakeFiles/FM_scheduling.dir/src/RTO.cpp.s
.PHONY : src/RTO.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FM_scheduling"
	@echo "... edit_cache"
	@echo "... periodic_simulator"
	@echo "... periodic_test"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BWP.o"
	@echo "... src/BWP.i"
	@echo "... src/BWP.s"
	@echo "... src/EDL.o"
	@echo "... src/EDL.i"
	@echo "... src/EDL.s"
	@echo "... src/RLP.o"
	@echo "... src/RLP.i"
	@echo "... src/RLP.s"
	@echo "... src/RTO.o"
	@echo "... src/RTO.i"
	@echo "... src/RTO.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

